---
cameras:
  - name: mobo-lospinos-n-color
    fire: "airport"
  - name: mobo-lospinos-n-mono
    fire: "airport"
  - name: mobo-lospinos-w-color
    fire: "airport"
  - name: mobo-lospinos-w-mono
    fire: "airport"
  - name: mobo-lospinos-e-color
    fire: "airport"
  - name: mobo-lospinos-e-mono
    fire: "airport"
  - name: mobo-lospinos-s-color
    fire: "airport"
  - name: mobo-lospinos-s-mono
    fire: "airport"
  - name: "Axis-MtnHighNorth1"
    fire: "bridge"
  - name: "Axis-MtnHighNorth2"
    fire: "bridge"
  - name: "Axis-MtnHighEast1"
    fire: "bridge"
  - name: "Axis-MtnHighEast2"
    fire: "bridge"
  - name: "Axis-MtnHighWest1"
    fire: "bridge"
  - name: "Axis-MtnHighWest2"
    fire: "bridge"
  - name: "Axis-Table1"
    fire: "bridge"
  - name: "Axis-Table2"
    fire: "bridge"
  - name: "Axis-RunningSprings1"
    fire: "line"
  - name: "Axis-RunningSprings2"
    fire: "line"
  - name: "Axis-KellerPeak1"
    fire: "line"
  - name: "Axis-KellerPeak2"
    fire: "line"
  - name: "Axis-MtDavid1"
  - name: "Axis-MtDavid2"
  - name: "Axis-HeapsPeak1"
  - name: "Axis-HeapsPeak2"
  - name: "Axis-SnowSummitWest"
    fire: "line"
  - name: "Axis-SnowSummitSouth"
    fire: "line"
  - name: "Axis-LakeviewBigBear1"
    fire: "line"
  - name: "Axis-PineMountainLA1"
  - name: "Axis-Johnstone1"
  - name: "Axis-StrawberryPeakArrowhead2"
  - name: "Axis-SantiagoPeakCalOESN"
    fire: "airport"
  - name: "Axis-SantiagoPeakCalOESS"
    fire: "airport"
  - name: "Axis-SantiagoOne1"
    fire: "airport"
  - name: "Axis-SantiagoOne2"
    fire: "airport"
  - name: "Axis-UpperBellNorth"
  - name: "Axis-UpperBellSouth"
  - name: "Axis-UpperTalegaNorth"
  - name: "Axis-Elsinore1"
    fire: "airport"
  - name: "Axis-Elsinore2"
    fire: "airport"
