#VERSION=0.1
name: hadolint

on: push

env:
    SVC_NAME: altertca-aggregator

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile